curl -d key=apikey -d first_name=David -d last_name=Smith http://51.81.84.150/api/user/new


Path: /api/user/new
Path: /api/user_list
Path: /api/user_info
Path: /api/user
Path: /api/user
Path: /api/user/<user_id>
Path: /api/user/<user_id>
Path: /api/user/<user_id>
Path: /api/fields
Path: /api/privileges
Path: /api/privileges
Path: /api/user/<user_id>/privileges
Path: /api/user/<user_id>/privileges
Path: /api/interviews
Path: /api/interviews
Path: /api/user/interviews
Path: /api/user/interviews
Path: /api/user/<user_id>/interviews
Path: /api/user/<user_id>/interviews
Path: /api/list
Path: /api/secret
Path: /api/login_url
Path: /api/resume_url
Path: /api/temp_url
Path: /api/session/new
Path: /api/session/question
Path: /api/session/action
Path: /api/session/back
Path: /api/session
Path: /api/file/<file_number>
Path: /api/playground
Path: /api/playground
Path: /api/playground
Path: /api/playground_install
Path: /api/playground/project
Path: /api/playground/project
Path: /api/playground/project
Path: /api/clear_cache
Path: /api/config
Path: /api/config
Path: /api/package
Path: /api/package
Path: /api/package_update_status
Path: /api/user/api
Path: /api/user/api
Path: /api/user/api
Path: /api/user/api
Path: /api/user/<user_id>/api
Path: /api/user/<user_id>/api
Path: /api/user/<user_id>/api
Path: /api/user/<user_id>/api
Path: /api/convert_file
Path: /api/interview_data
Path: /api/stash_data
Path: /api/retrieve_stashed_data
